name: chatbot
version: 0.3.1+6
description: ChatBot

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  intl: ^0.19.0
  flutter_riverpod: ^2.6.1

  archive: ^3.6.1
  screenshot: ^3.0.0
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_image_compress: ^2.3.0

  langchain: ^0.7.7+1
  langchain_openai: ^0.7.2+5
  langchain_google: ^0.6.4+1
  langchain_community: ^0.3.2+2

  animate_do: ^3.3.4
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  audioplayers: ^6.1.0
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.1.2
  image_gallery_saver_plus: ^3.0.5

  markdown: ^7.2.2
  flutter_math_fork: ^0.7.2
  flutter_markdown: ^0.7.4+2
  flutter_highlighter: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.7
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen
